### ISSUE TITLE
Contact form to send Mail to us with customer message

### ISSUE THREAD

**Issue by elhenro** [v1bes/v1bervue#13]

**Comment by elhenro** [comment]
Wohl am einfachsten via Php und dann Ajax request auf eigene Unterseite, so dass unser server die mail sendet? @marcolilli du hast da auch Erfahrung, oder?

**Comment by elhenro** [comment]
jetzt aktuell siehe #dev-mail

**Comment by marcolilli** [comment]
jo easy ich schau, dass ichs die tage hinkrieg
