### ISSUE TITLE
missing favicon

### ISSUE THREAD

**Issue by elhenro** [v1bes/v1bervue#16]
current facvicon is still vue icon

**Comment by Moercell** [comment]
was machen wir? v1b oder nur das v ?

**Comment by elhenro** [comment]
Vllt nur 'v' oder 'v1'?

**Comment by Moercell** [comment]
ok jetzt wird so ziemlich alles unterstützt was geht

**Comment by elhenro** [comment]
wie meinst du?

**Comment by Moercell** [comment]
naja alle größen und auch wenn man in safari das pinnt und so

**Comment by elhenro** [comment]
Ah nice
