### ISSUE TITLE
marcos name is too short

### ISSUE THREAD

**Issue by Moercell** [v1bes/v1bervue#3]
<img width="400" alt="bildschirmfoto 2018-03-13 um 19 04 51" src="https://user-images.githubusercontent.com/11335897/37360810-89ff64ce-26f1-11e8-9ea0-0c89f9cb7d36.png">

**Comment by elhenro** [comment]
@marcolilli middle name vielleicht? :dango:

**Comment by Moercell** [comment]
ich glaube is gibt ein css ding um ihm zu sagen das er umbrechen soll
