### ISSUE TITLE
layout problem with projects on big screens (>1700px)

### ISSUE THREAD

**Issue by Moercell** [v1bes/v1bervue#4]
<img width="1920" alt="bildschirmfoto 2018-03-13 um 19 07 11" src="https://user-images.githubusercontent.com/11335897/37360993-1a0a3f44-26f2-11e8-9914-4b0d59be7447.png">

**Comment by elhenro** [comment]
dann kacheln am besten in 3er reihe + skalierbar?

**Comment by Moercell** [comment]
naja 3er reihe ist blöde wenn wir nur 4 items haben ... aber wir können die dinger fast so groß skalieren wie wir wollen
