### ISSUE TITLE
responsive Problems

### ISSUE THREAD

**Issue by Moercell** [v1bes/v1bervue#5]
<img width="374" alt="bildschirmfoto 2018-03-13 um 19 16 15" src="https://user-images.githubusercontent.com/11335897/37361416-23d8a24e-26f3-11e8-9a65-08cd9513c152.png">

ich glaube der text "We are a web development collective" und unsere bilder sind nur etwas zu groß

**Comment by elhenro** [comment]
nehme an du meinst den overflow rechts?
ja text skalierbar, oder?

**Comment by Moercell** [comment]
ja einfach noch ein media query für die größe

**Comment by Moercell** [comment]
hat sich einfach so gefixed ... nicht sicher warum
