### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by Moercell** [v1bes/v1bervue#6]

**Comment by elhenro** [comment]
@Moercell @marcolilli schaut mal dev-contact branch an..
ich habe eine art kontakt formular gebaut, die uns eine email mit der nachricht schicken soll, so dass wir darauf antworten können.
ich wollte erst mit mailgun und emailjs vom frontend die email senden, aber das geht nicht wirklich..
deswegen würde ich es vllt doch vom server mit php machen? was denkt ihr ? ajax?

**Comment by elhenro** [comment]
@Moercell @marcolilli denke dann werde ich das selbst umsetzten
