### ISSUE TITLE
unable to scroll on top of "projectsBox" (mobile)

### ISSUE THREAD

**Issue by Moercell** [v1bes/v1bervue#9]
die projectsBoxen sind halt so gemacht das der Effekt auf mit touch funktioniert also gibt es zwei Möglichkeiten:

- wir entfernen den Effekt auf mobile und es sind einfach nur Bilder
- dir machen die projectsBoxen etwas kleiner so das am Rand mehr platz zum hoch swipen ist

**Bitte jetzt abstimmen**

**Comment by elhenro** [comment]
1. wäre also ab screen width $smallscreen -> kein effekt ? vllt kein effekt ab der größe wo man natürlich auf dem bild scrollen wollen würde?

**Comment by Moercell** [comment]
fürs erste mal geschlossen

**Comment by elhenro** [comment]
>fürs erste mal geschlossen
das machts nicht wirklich informativer.. :D

**Comment by Moercell** [comment]
Achso ja das steht in dem commit davor ... der hat das issue irgendwie nicht gleich geschlossen

**Comment by elhenro** [comment]
ok cool also erst mal raus genommen..
